server:
  port: 23010

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hadoop000:3306/yunshang_oa?useSSL=false&serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Qhy123456

# 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl